version: '2'
services:
  recipebook-backend:
    container_name: reicpebook-backend
    build:
      context: ../RecipeBookBackend/recipebook/
      dockerfile: ./Dockerfile
    ports:
      - 905:905
    networks:
      - spring-cloud-network


  shoppinglist-backend:
    container_name: shoppinglist-backend
    build:
      context: ../RecipeBookBackend/shoppinglist
      dockerfile: ./Dockerfile
    ports:
      - 906:905
    networks:
      - spring-cloud-network


  recipebook-frontend:
    container_name: recipebook-frontend
    build:
      context: ../RecipeBookFrontend/
      dockerfile: ./Dockerfile
    ports:
      - 2017:2017


networks:
  spring-cloud-network:
    driver: bridge